// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byxuuogoclogoqsurlde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5eHV1b2dvY2xvZ29xc3VybGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTU5NzIsImV4cCI6MjA2ODA3MTk3Mn0.26jrvgBCmUgO5JaAZgq69u7kUs2Vvi_6Vr9Ozy_QIEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});